### ISSUE TITLE
The number of obtained marker genes is very low.

### ISSUE THREAD

**Issue by bioinformaticspcj** [pinellolab/dictys#40]
Dear Lingfei,

Thanks for your valuable suggestions in #37 . I have changed the motif file myself and the dictys works. However, only two marker genes were output. I got some error information as follows:

  Traceback (most recent call last):
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/chromatin.py", line 129, in wellington
    d2 = shell.cmdfile(cmd,[],quiet=False,cd=True)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/utils/shell.py", line 181, in cmdfile
    raise RuntimeError('Command failed, possibly due to program error: ' + cmda)
RuntimeError: Command failed, possibly due to program error: /data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/scripts/chromatin_wellington.sh /data/share/pcj/CNE_analysis/single_Cell_GRN/tmp_static/Subset1/reads.bam /data/share
make: *** [makefiles/common.mk:141: tmp_static/Subset1/footprints.bed] Error 1
Traceback (most recent call last):
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 791, in reconstruct
    model.gen_params({'G_obs':model.tensor(dt0.astype(int),dtype=torch.int)})
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 635, in gen_params
    super().gen_params(observations)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 530, in gen_params
    t2=torch.pca_lowrank(t1,q=self.npc,center=False,niter=50)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/torch/_lowrank.py", line 274, in pca_lowrank
    return _svd_lowrank(A, q, niter=niter, M=None)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/torch/_lowrank.py", line 170, in _svd_lowrank
    U, S, Vh = torch.linalg.svd(B_t, full_matrices=False)
torch._C._LinAlgError: linalg.svd: The algorithm failed to converge because the input matrix contained non-finite values.
make: *** [makefiles/common.mk:172: tmp_static/Subset7/net_weight.tsv.gz] Error 1
Traceback (most recent call last):
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/__main__.py", line 13, in <module>
    docstringrunner(__package__)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 340, in docstringrunner
    run_args(pkgname,funcs,args)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/docstring2argparse/__init__.py", line 330, in run_args
    return func(*a,**ka)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 791, in reconstruct
    model.gen_params({'G_obs':model.tensor(dt0.astype(int),dtype=torch.int)})
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 635, in gen_params
    super().gen_params(observations)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/dictys/network.py", line 530, in gen_params
    t2=torch.pca_lowrank(t1,q=self.npc,center=False,niter=50)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/torch/_lowrank.py", line 274, in pca_lowrank
    return _svd_lowrank(A, q, niter=niter, M=None)
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/envs/dictys/lib/python3.9/site-packages/torch/_lowrank.py", line 170, in _svd_lowrank
    U, S, Vh = torch.linalg.svd(B_t, full_matrices=False)
torch._C._LinAlgError: linalg.svd: The algorithm failed to converge because the input matrix contained non-finite values.

The format of input narrowPeak file (footprints.bed) is as follows:
chr1	24612366	24613560	peak1:chr1:24612366:24613560:172.29200
chr1	20819892	20820782	peak2:chr1:20819892:20820782:136.96100
chr14	54517060	54518015	peak3:chr14:54517060:54518015:135.39000
chr15	75085437	75087073	peak4:chr15:75085437:75087073:135.39000
chr14	119007166	119007934	peak5:chr14:119007166:119007934:134.67700
chr2	150362345	150363260	peak6:chr2:150362345:150363260:134.64800
chr2	148731571	148732731	peak7:chr2:148731571:148732731:133.37600
chr12	91383694	91384900	peak8:chr12:91383694:91384900:132.47700
chr13	119689853	119690996	peak9:chr13:119689853:119690996:131.85300
chr9	36767265	36768581	peak10:chr9:36767265:36768581:131.45500

Do I need to change the input narrowPeak files to run? If yes, could you give me some advice to change the files.

Many thanks!

Best,
Bob

**Comment by lingfeiwang** [comment]
Hi Bob,

Because you are using bulk ATAC-seq data, you are expected to find a weaker contrast, including fewer regulation marker genes. You can try to change the parameters in regulation marker gene discovery. The errors suggest something wrong with your input data but are unrelated to the number of marker genes here.

Lingfei
