### ISSUE TITLE
creating with "data/coord_rna.tsv.gz"

### ISSUE THREAD

**Issue by OneHitKO** [pinellolab/dictys#65]
Dear development team, 

I am excited to try Dictys (dynamic mode), but am having problem identifying where to create the`data/coord_rna.tsv.gz` file. My current data directory looks like this:
```
WARNING:root:Cannot find static.mk or subsets.txt. Skipping static network inference checks.
Traceback (most recent call last):
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/dictys/scripts/helper/makefile_check.py", line 317, in <module>
    coord_rna=pd.read_csv(pjoin(dirdata,'coord_rna.tsv.gz'),header=0,index_col=0,sep='\t')
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/site-packages/pandas/io/common.py", line 755, in get_handle
    handle = gzip.GzipFile(  # type: ignore[assignment]
  File "/g/saka/Kristy/software/envs/dictys/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/coord_rna.tsv.gz'
```

Would you be able to point out in the tutorial how I can create this?  
Thanks for the help and for the cool tool! 

Best,
Kristy

**Comment by OneHitKO** [comment]
(sorry, this is not with the tutorial, but with my own multiome dataset)

**Comment by lingfeiwang** [comment]
Hi Kristy,

Have you tried our dynamic GRN tutorial such as full-skin? From its input data files you can figure out their formats.

Best,
Lingfei

**Comment by OneHitKO** [comment]
Dear Lingfei, thanks for the quick reply! Good point, I just realized it is a file from the STREAM analysis of notebook 1. All clear now. :)

**Comment by jzw1999** [comment]
Hi Kristy, have you been able to find out where this `data/coord_rna.tsv.gz` file emerges? Is that a product of the dictys workflow at some point? I'm also preparing to run the dynamic inference and am eager to know. (:

**Comment by OneHitKO** [comment]
hey yes! it's a file you will have to provide from your own analysis, but you can see the format by downloading the test data here: `dictys_helper repodown.sh zenodo full-skin.tar.xz` (from first chunk of this tutorial: https://github.com/pinellolab/dictys/blob/master/doc/tutorials/full-skin/notebooks/main1.ipynb). 

the coords file is basically a multidimensional embedding that dictys uses to reconstruct a trajectory / group cells in sliding window bins. but you need to use it along with other files in above tutorial to ultimately create a trajectory file in h5 format (in beginning of 2nd part full-skin tutorial) before running dynamic dictys. hope that helps :)
