### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by ASasasdasfasfasfasfasf** [pinellolab/dictys#72]
Hello
I encountered the following error while running 'make - f makefiles/static. mk - j 32- k CPU | | true'. What is this

[bam_sort_core] merging from 6 files and 4 in-memory blocks...
Traceback (most recent call last):
  File "/work/home/fenggangyi/miniforge3/envs/dictys/bin/macs2", line 653, in <module>
    main()
  File "/work/home/fenggangyi/miniforge3/envs/dictys/bin/macs2", line 49, in main
    from MACS2.callpeak_cmd import run
  File "/work/home/fenggangyi/miniforge3/envs/dictys/lib/python3.9/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/work/home/fenggangyi/miniforge3/envs/dictys/lib/python3.9/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 206, in init MACS2.IO.Parser
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by lingfeiwang** [comment]
It appears a macs2 issue. Does this help: https://stackoverflow.com/questions/25752444/scipy-error-numpy-dtype-size-changed-may-indicate-binary-incompatibility-and? If not, please raise an issue to macs2.
